version: 2.1
orbs:
  commitlint: conventional-changelog/commitlint@1.0
jobs:
  lint:
    docker:
      - image: circleci/node:16.13-browsers
    steps:
      - checkout
      - restore_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:16.13-browsers
    steps:
      - checkout
      - restore_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
workflows:
  version: 2
  build:
    jobs:
      - commitlint/lint:
            max-count: 1000
      - lint
      - test

