version: 2.1

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:16.13-browsers

orbs:
  commitlint: conventional-changelog/commitlint@1.0

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist/build
  docs-build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run docs:build
      - persist_to_workspace:
          root: .
          paths:
            - dist/docs
  release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - attach_workspace:
          at: ~/project
      - run: ls dist
      - run: ls dist/build
      - run:
          name: release
          command: npm run semantic-release

workflows:
  version: 2
  main:
    jobs:
      - commitlint/lint:
          name: commitlint
          max-count: 1000
          filters:
            branches:
              ignore:
                - main
      - lint
      - test
      - build:
          requires:
            - commitlint
            - lint
            - test
          filters:
            branches:
              only:
                - main
      - release:
          requires:
            - commitlint
            - lint
            - test
            - build
          filters:
            branches:
              only:
                - main

