version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/node:16.13-browsers
    steps:
      - checkout
      - restore_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:16.13-browsers
    steps:
      - checkout
      - restore_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: iget-editor-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
workflows:
    test:
      jobs:
        - lint
        - test
